    image: node:latest

    stages:
      - build

    cache:
      paths:
        - node_modules/

    install_dependencies:
      stage: build
      script:
        - yarnd global add node-gyp; yarn install
      artifacts:
        paths:
          - node_modules/

    build_electron:
      stage: build
      script:
        - yarn run dist
      artifacts:
        paths:
          - dist/

